version: '3.1'
services:
  app:
    build: .
    container_name: user-api
    restart: always
    environment:
      - DB_IP=postgresql
      - DB_NAME=users_db
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=password
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users_db

